server:
  port: 8888

spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          default-label: "main"
          uri: "git@github.com:wallacyrezende/ms-scloud-sboot-configs.git"
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
          strict-host-key-checking: true
          passphrase: 'theo2022'
          ignore-local-ssh-settings: true
#          private-key: ${SSH_KEY}
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-128-CBC,0BBABB735977C6346A475F94FFD0A9C6

            3VhovtwHetmtCb+daV7lf2SKn4u3DLDXtS69Lq1r8vtDMpt/kTIyBQZYhDQtDsB1
            NbklA5MgVkXehZPrkHdA9xUyK1Yaa1yPvhItSLw/WZVfSawTZEoAr1mm3enuW5tv
            KXhkI8H3JCY4++hHrUXn635AysJqznyEoXIfa7pTqq8=
            -----END EC PRIVATE KEY-----
