server:
  port: 8443

spring:
  application:
    name: auth-server
  config:
    import: optional:configserver:http://localhost:8888/
    cloud:
      config:
        profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka