server:
    port: 8080

spring:
  application:
    name: user-release
  cloud:
      config:
        uri: http://localhost:8888
  devtools:
    add-properties: true
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false

eureka:
    instance:
      instance-id: user-release:${spring.application.instance_id:8080}
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
