spring:
  application:
    name: user-release
  devtools:
    add-properties: true
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false

server:
    port: 8080

eureka:
    instance:
      instance-id: user-release:${spring.application.instance_id:8080}
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
